<?php



/**
 *  Preprocess page.
 */
function custom_mobmenu_preprocess_page(&$variables) {
  drupal_add_css(drupal_get_path('module', 'custom_mobmenu') . '/css/custom_mobmenu.css');
  drupal_add_js(drupal_get_path('module', 'custom_mobmenu') . '/js/custom_mobmenu.js');
  		
  $only_main_menu = variable_get('main_menu_only', 1);
  $menu_block = array();
  if ($only_main_menu) {
    $menu_block = block_load('menu', 'main-menu');
	$menu_block = _block_get_renderable_array(_block_render_blocks(array($menu_block)));	
	unset($menu_block['menu_main-menu']['#contextual_links']);
	drupal_add_js(array('custom_mobmenu' => array('menu_block' => '#block-menu-main-menu')), 'setting');
  }
  else {
  	global $language;
	$menu_block_id = variable_get('menu_block_id_' . $language->language, '');
    $menu_block = module_invoke('menu_block', 'block_view', $menu_block_id);	
    $menu_block = $menu_block['content']; 	
	drupal_add_js(array('custom_mobmenu' => array('menu_block' => '.menu-block-' . $menu_block_id)), 'setting');
  }
  $config = custom_mobmenu_get_config();
  drupal_add_js(array('custom_mobmenu' => array('config' => $config)), 'setting');
  $html = '<div id="mob_menu_wrap"><div class="dl-menu menu_header" style="display:none;"><span class="head_cont"></span><span class="menu_close">&#10006;</span></div>';
  $html .= render($menu_block);
  $html .= '</div>';	
  
  
  $mobile_menu = '<div id="dl-menu" class="dl-menuwrapper" style="display: none;"><button class="dl-trigger">' . t('Menu') .'</button>' . $html . '</div>';

  $variables['page']['header']['#prefix'] = $mobile_menu;
  
  	
}

/**
 * Implements hook_menu().
 */
function custom_mobmenu_menu() {
  $items = array();
  $items['admin/config/system/mobmenu'] = array(
		'title' => 'Mobmenu configuration',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('custom_mobmenu_config'),
		'access arguments' => array('administer site configuration'),
		'type' => MENU_NORMAL_ITEM,
	);


  return $items;
} 

/**
 * Configuration page for mobmenu.
 */
function custom_mobmenu_config() {  
  $form['main_menu_only'] = array(
    '#type' => 'checkbox', 
    '#title' => t('Used only main-menu'),
    '#default_value' => variable_get('main_menu_only', 1),
  );
  
  $langs = language_list();
  foreach ($langs as $id => $lang) {
    $form['menu_block_id_' . $id] = array(
      '#type' => 'textfield', 
      '#title' => t('Menu block id for !ln', array('!ln' => $lang->native)), 
      '#default_value' => variable_get('menu_block_id_' . $id, ''), 
      '#states' => array(
        'visible' => array(
          'input[name="main_menu_only"]' => array('checked' => FALSE)
        )
      ),
    );   	
  }  
  
  $form['custom_mobmenu_bg_color'] = array(
    '#type' => 'textfield', 
    '#size' => 20, 
    '#title' => t('Background color for mobile menu'), 
    '#default_value' => variable_get('custom_mobmenu_bg_color', '#46adb8'), 
  );
  
  $form['custom_mobmenu_header_bg_color'] = array(
    '#type' => 'textfield', 
    '#size' => 20, 
    '#title' => t('Background color for header mobile menu'), 
    '#default_value' => variable_get('custom_mobmenu_header_bg_color', '#2d7a91'), 
  );
  
  $form['custom_mobmenu_text_color'] = array(
    '#type' => 'textfield', 
    '#size' => 20, 
    '#title' => t('Text color for mobile menu'), 
    '#default_value' => variable_get('custom_mobmenu_text_color', '#FFFFFF'), 
  );
    $form['custom_mobmenu_border_color'] = array(
    '#type' => 'textfield', 
    '#size' => 20, 
    '#title' => t('Border color for mobile menu'), 
    '#default_value' => variable_get('custom_mobmenu_border_color', '#FFFFFF'), 
  );
     
  return system_settings_form($form);	
}

/**
 * Get config information for mobile menu.
 */
function custom_mobmenu_get_config() {
  $config = array();
  
  $config['bg_color'] = variable_get('custom_mobmenu_bg_color', '#46adb8');
  $config['header_bg_color'] = variable_get('custom_mobmenu_header_bg_color', '#2d7a91');
  $config['text_color'] = variable_get('custom_mobmenu_text_color', '#FFFFFF');   	
  $config['border_color'] = variable_get('custom_mobmenu_border_color', '#FFFFFF');
  
  return $config;
}

